use super::storage::store::Store;
use crate::string_enum;
use std::sync::Arc;

string_enum! {
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    pub enum ComdType {
        default = Exec;
        Exec => "EXEC",

        PING => "PING",
        ECHO => "ECHO",
        INFO => "INFO",
        FLUSH => "FLUSH",
        DBSIZE => "DBSIZE",
        TYPE => "TYPE",
        BGSAVE => "BGSAVE",

        GET => "GET",
        SET => "SET",
        SETNX => "SETNX",
        SETEX => "SETEX",
        PSETEX => "PSETEX",
        GETDEL => "GETDEL",
        GETSET => "GETSET",
        GETEX => "GETEX",
        MSET => "MSET",
        MSETNX => "MSETNX",
        MGET => "MGET",
        INCR => "INCR",
        DECR => "DECR",
        INCRBY => "INCRBY",
        DECRBY => "DECRBY",
        INCRBYFLOAT => "INCRBYFLOAT",
        APPEND => "APPEND",
        STRLEN => "STRLEN",
        GETRANGE => "GETRANGE",
        SETRANGE => "SETRANGE",

        DEL => "DEL",
        UNLINK => "UNLINK",
        EXISTS => "EXISTS",
        TTL => "TTL",
        PTTL => "PTTL",
        EXPIRE => "EXPIRE",
        PEXPIRE => "PEXPIRE",
        EXPIREAT => "EXPIREAT",
        PERSIST => "PERSIST",
        RENAME => "RENAME",
        RENAMENX => "RENAMENX",
        COPY => "COPY",
        RANDOMKEY => "RANDOMKEY",
        KEYS => "KEYS",
        SCAN => "SCAN",

        HSET => "HSET",
        HSETNX => "HSETNX",
        HGET => "HGET",
        HMGET => "HMGET",
        HMSET => "HMSET",
        HGETALL => "HGETALL",
        HDEL => "HDEL",
        HEXISTS => "HEXISTS",
        HLEN => "HLEN",
        HKEYS => "HKEYS",
        HVALS => "HVALS",
        HINCRBY => "HINCRBY",
        HINCRBYFLOAT => "HINCRBYFLOAT",

        LPUSH => "LPUSH",
        RPUSH => "RPUSH",
        LPOP => "LPOP",
        RPOP => "RPOP",
        LLEN => "LLEN",
        LINDEX => "LINDEX",
        LSET => "LSET",
        LRANGE => "LRANGE",
        LTRIM => "LTRIM",
        LREM => "LREM",
        LINSERT => "LINSERT",
        LPOS => "LPOS",
        LMOVE => "LMOVE",
        RPOPLPUSH => "RPOPLPUSH",

        SADD => "SADD",
        SREM => "SREM",
        SISMEMBER => "SISMEMBER",
        SMISMEMBER => "SMISMEMBER",
        SMEMBERS => "SMEMBERS",
        SCARD => "SCARD",
        SPOP => "SPOP",
        SRANDMEMBER => "SRANDMEMBER",
        SMOVE => "SMOVE",
        SUNION => "SUNION",
        SINTER => "SINTER",
        SDIFF => "SDIFF",
        SUNIONSTORE => "SUNIONSTORE",
        SINTERSTORE => "SINTERSTORE",
        SDIFFSTORE => "SDIFFSTORE",
        SINTERCARD => "SINTERCARD",

        ZADD => "ZADD",
        ZREM => "ZREM",
        ZSCORE => "ZSCORE",
        ZMSCORE => "ZMSCORE",
        ZRANK => "ZRANK",
        ZREVRANK => "ZREVRANK",
        ZCARD => "ZCARD",
        ZCOUNT => "ZCOUNT",
        ZINCRBY => "ZINCRBY",
        ZRANGE => "ZRANGE",
        ZREVRANGE => "ZREVRANGE",
        ZRANGEBYSCORE => "ZRANGEBYSCORE",
        ZREVRANGEBYSCORE => "ZREVRANGEBYSCORE",
        ZPOPMIN => "ZPOPMIN",
        ZPOPMAX => "ZPOPMAX",
        ZUNIONSTORE => "ZUNIONSTORE",
        ZINTERSTORE => "ZINTERSTORE",
        ZRANDMEMBER => "ZRANDMEMBER",

        JSONSET => "JSON.SET",
        JSONGET => "JSON.GET",
        JSONDEL => "JSON.DEL",
        JSONFORGET => "JSON.FORGET",
        JSONTYPE => "JSON.TYPE",
        JSONNUMINCRBY => "JSON.NUMINCRBY",
        JSONNUMMULTBY => "JSON.NUMMULTBY",
        JSONSTRAPPEND => "JSON.STRAPPEND",
        JSONSTRLEN => "JSON.STRLEN",
        JSONARRAPPEND => "JSON.ARRAPPEND",
        JSONARRINDEX => "JSON.ARRINDEX",
        JSONARRINSERT => "JSON.ARRINSERT",
        JSONARRLEN => "JSON.ARRLEN",
        JSONARRPOP => "JSON.ARRPOP",
        JSONARRTRIM => "JSON.ARRTRIM",
        JSONOBJKEYS => "JSON.OBJKEYS",
        JSONOBJLEN => "JSON.OBJLEN",
        JSONTOGGLE => "JSON.TOGGLE",
        JSONCLEAR => "JSON.CLEAR",
    }
}

pub fn execute(parts: &[&str], store: &Arc<Store>, out: &mut Vec<u8>) {
    if parts.is_empty() {
        out.extend_from_slice(b"-ERR invalid command\r\n");
        return;
    }

    let cmd = ComdType::from(parts[0]);
    match cmd {
        ComdType::PING => connection::ping(parts, out),
        ComdType::ECHO => connection::echo(parts, out),
        ComdType::INFO => connection::info(store, out),
        ComdType::FLUSH => connection::flush(store, out),
        ComdType::DBSIZE => connection::dbsize(store, out),
        ComdType::TYPE => connection::type_of(parts, store, out),
        ComdType::BGSAVE => connection::bgsave(store, out),

        ComdType::GET => string::get(parts, store, out),
        ComdType::SET => string::set(parts, store, out),
        ComdType::SETNX => string::setnx(parts, store, out),
        ComdType::SETEX => string::setex(parts, store, out),
        ComdType::PSETEX => string::psetex(parts, store, out),
        ComdType::GETDEL => string::getdel(parts, store, out),
        ComdType::GETSET => string::getset(parts, store, out),
        ComdType::GETEX => string::getex(parts, store, out),
        ComdType::MSET => string::mset(parts, store, out),
        ComdType::MSETNX => string::msetnx(parts, store, out),
        ComdType::MGET => string::mget(parts, store, out),
        ComdType::INCR => string::incr(parts, store, out),
        ComdType::DECR => string::decr(parts, store, out),
        ComdType::INCRBY => string::incrby(parts, store, out),
        ComdType::DECRBY => string::decrby(parts, store, out),
        ComdType::INCRBYFLOAT => string::incrbyfloat(parts, store, out),
        ComdType::APPEND => string::append(parts, store, out),
        ComdType::STRLEN => string::strlen(parts, store, out),
        ComdType::GETRANGE => string::getrange(parts, store, out),
        ComdType::SETRANGE => string::setrange(parts, store, out),

        ComdType::DEL => keys::del(parts, store, out),
        ComdType::UNLINK => keys::unlink(parts, store, out),
        ComdType::EXISTS => keys::exists_check(parts, store, out),
        ComdType::TTL => keys::ttl_check(parts, store, out),
        ComdType::PTTL => keys::pttl_check(parts, store, out),
        ComdType::EXPIRE => keys::expire(parts, store, out),
        ComdType::PEXPIRE => keys::pexpire(parts, store, out),
        ComdType::EXPIREAT => keys::expireat(parts, store, out),
        ComdType::PERSIST => keys::persist(parts, store, out),
        ComdType::RENAME => keys::rename(parts, store, out),
        ComdType::RENAMENX => keys::renamenx(parts, store, out),
        ComdType::COPY => keys::copy(parts, store, out),
        ComdType::RANDOMKEY => keys::randomkey(parts, store, out),
        ComdType::KEYS => keys::keys(parts, store, out),
        ComdType::SCAN => scan::scan(parts, store, out),

        ComdType::HSET => hash::hset(parts, store, out),
        ComdType::HSETNX => hash::hsetnx(parts, store, out),
        ComdType::HGET => hash::hget(parts, store, out),
        ComdType::HMGET => hash::hmget(parts, store, out),
        ComdType::HMSET => hash::hmset(parts, store, out),
        ComdType::HGETALL => hash::hgetall(parts, store, out),
        ComdType::HDEL => hash::hdel(parts, store, out),
        ComdType::HEXISTS => hash::hexists(parts, store, out),
        ComdType::HLEN => hash::hlen(parts, store, out),
        ComdType::HKEYS => hash::hkeys(parts, store, out),
        ComdType::HVALS => hash::hvals(parts, store, out),
        ComdType::HINCRBY => hash::hincrby(parts, store, out),
        ComdType::HINCRBYFLOAT => hash::hincrbyfloat(parts, store, out),

        ComdType::LPUSH => list::lpush(parts, store, out),
        ComdType::RPUSH => list::rpush(parts, store, out),
        ComdType::LPOP => list::lpop(parts, store, out),
        ComdType::RPOP => list::rpop(parts, store, out),
        ComdType::LLEN => list::llen(parts, store, out),
        ComdType::LINDEX => list::lindex(parts, store, out),
        ComdType::LSET => list::lset(parts, store, out),
        ComdType::LRANGE => list::lrange(parts, store, out),
        ComdType::LTRIM => list::ltrim(parts, store, out),
        ComdType::LREM => list::lrem(parts, store, out),
        ComdType::LINSERT => list::linsert(parts, store, out),
        ComdType::LPOS => list::lpos(parts, store, out),
        ComdType::LMOVE => list::lmove(parts, store, out),
        ComdType::RPOPLPUSH => list::rpoplpush(parts, store, out),

        ComdType::SADD => set::sadd(parts, store, out),
        ComdType::SREM => set::srem(parts, store, out),
        ComdType::SISMEMBER => set::sismember(parts, store, out),
        ComdType::SMISMEMBER => set::smismember(parts, store, out),
        ComdType::SMEMBERS => set::smembers(parts, store, out),
        ComdType::SCARD => set::scard(parts, store, out),
        ComdType::SPOP => set::spop(parts, store, out),
        ComdType::SRANDMEMBER => set::srandmember(parts, store, out),
        ComdType::SMOVE => set::smove(parts, store, out),
        ComdType::SUNION => set::sunion(parts, store, out),
        ComdType::SINTER => set::sinter(parts, store, out),
        ComdType::SDIFF => set::sdiff(parts, store, out),
        ComdType::SUNIONSTORE => set::sunionstore(parts, store, out),
        ComdType::SINTERSTORE => set::sinterstore(parts, store, out),
        ComdType::SDIFFSTORE => set::sdiffstore(parts, store, out),
        ComdType::SINTERCARD => set::sintercard(parts, store, out),

        ComdType::ZADD => zset::zadd(parts, store, out),
        ComdType::ZREM => zset::zrem(parts, store, out),
        ComdType::ZSCORE => zset::zscore(parts, store, out),
        ComdType::ZMSCORE => zset::zmscore(parts, store, out),
        ComdType::ZRANK => zset::zrank(parts, store, out),
        ComdType::ZREVRANK => zset::zrevrank(parts, store, out),
        ComdType::ZCARD => zset::zcard(parts, store, out),
        ComdType::ZCOUNT => zset::zcount(parts, store, out),
        ComdType::ZINCRBY => zset::zincrby(parts, store, out),
        ComdType::ZRANGE => zset::zrange(parts, store, out),
        ComdType::ZREVRANGE => zset::zrevrange(parts, store, out),
        ComdType::ZRANGEBYSCORE => zset::zrangebyscore(parts, store, out),
        ComdType::ZREVRANGEBYSCORE => zset::zrevrangebyscore(parts, store, out),
        ComdType::ZPOPMIN => zset::zpopmin(parts, store, out),
        ComdType::ZPOPMAX => zset::zpopmax(parts, store, out),
        ComdType::ZUNIONSTORE => zset::zunionstore(parts, store, out),
        ComdType::ZINTERSTORE => zset::zinterstore(parts, store, out),
        ComdType::ZRANDMEMBER => zset::zrandmember(parts, store, out),

        ComdType::JSONSET => json::json_set(parts, store, out),
        ComdType::JSONGET => json::json_get(parts, store, out),
        ComdType::JSONDEL => json::json_del(parts, store, out),
        ComdType::JSONFORGET => json::json_forget(parts, store, out),
        ComdType::JSONTYPE => json::json_type(parts, store, out),
        ComdType::JSONNUMINCRBY => json::json_numincrby(parts, store, out),
        ComdType::JSONNUMMULTBY => json::json_nummultby(parts, store, out),
        ComdType::JSONSTRAPPEND => json::json_strappend(parts, store, out),
        ComdType::JSONSTRLEN => json::json_strlen(parts, store, out),
        ComdType::JSONARRAPPEND => json::json_arrappend(parts, store, out),
        ComdType::JSONARRINDEX => json::json_arrindex(parts, store, out),
        ComdType::JSONARRINSERT => json::json_arrinsert(parts, store, out),
        ComdType::JSONARRLEN => json::json_arrlen(parts, store, out),
        ComdType::JSONARRPOP => json::json_arrpop(parts, store, out),
        ComdType::JSONARRTRIM => json::json_arrtrim(parts, store, out),
        ComdType::JSONOBJKEYS => json::json_objkeys(parts, store, out),
        ComdType::JSONOBJLEN => json::json_objlen(parts, store, out),
        ComdType::JSONTOGGLE => json::json_toggle(parts, store, out),
        ComdType::JSONCLEAR => json::json_clear(parts, store, out),

        _ => out.extend_from_slice(b"-ERR unknown command\r\n"),
    }
}

pub mod connection;
pub mod hash;
pub mod json;
pub mod keys;
pub mod list;
pub mod scan;
pub mod set;
pub mod string;
pub mod zset;
