version: "3"

vars:
   BINARY: flash_db
   VERSION: v0.1.0

tasks:
   run:
      desc: Run the binary
      cmds:
         - task: build
         - target/release/{{.BINARY}}

   build:
      desc: Release build
      cmds:
         - cargo build --release

   test:
      desc: Run tests
      cmds:
         - cargo test

   bench-key-flash:
      desc: benchmark key operations on flash db
      cmds:
         - cd bench && go run . -m key

   bench-key-redis:
      desc: benchmark key operations on redis
      cmds:
         - cd bench && go run . -p 6379 -m key

   bench-pub-flash:
      desc: benchmark pub operations on flash db
      cmds:
         - cd bench && go run . -m pub

   bench-pub-redis:
      desc: benchmark pub operations on redis
      cmds:
         - cd bench && go run . -p 6379 -m pub

   bench-flash:
      desc: benchmark flash db
      cmds:
         - cd bench && go run . 
   bench-redis:
      desc: benchmark redis
      cmds:
         - cd bench && go run . -p 6379
